/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SupabaseRandom': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { success: boolean; randomNumber: number; id?: string; message: string }> | ApiResponse<500, { success: boolean; error: string }>, never>
    'SimpleHello': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string }>, never>
    'FlightSearch': ApiRouteHandler<{ origin: string; destination: string; departureDate: string; returnDate?: string }, ApiResponse<200, { success: boolean; tripsWithDeals: Array<{ tripId: number; origin: string; destination: string; stopCount: number; duration: number; isRound: boolean; departureDate: string; departureTime: string; returnDate: unknown; returnTime: unknown; legs: Array<{ id: number; inbound: boolean; connectionTime: unknown; flight: { id: number; flightNumber: string; airline: string; origin: string; destination: string; departureDate: string; departureTime: string; arrivalDate: string; arrivalTime: string; duration: number } }>; deals: Array<{ id: number; source: string; provider: string; price: number; link: string; expiryDate: string }> }> }> | ApiResponse<400, { success: boolean; error: string }>, never>
  }
}